-- l3build configuration for the nycbullets package.
--
-- The *.def data files, the key tables and the fonts are generated by the
-- Python pipeline in the parent directory (`make latex` there) before
-- l3build runs.

module = "nycbullets"

sourcefiles     = {"*.dtx", "*.ins", "*.def", "*.ttf"}
installfiles    = {"*.sty", "*.def", "*.ttf"}
-- The key tables are \input by the documentation.
docfiles        = {"nycbullets-keytable-*.tex", "nycbullets-credits.tex"}
textfiles       = {"README.md"}

typesetexe   = "lualatex"
typesetfiles = {"nycbullets.dtx"}
typesetruns  = 3

checkengines = {"luatex"}
checkruns    = 1

tdslocations = {
  "fonts/truetype/public/nycbullets/*.ttf",
}
