-- l3build configuration for the nycbullets package.
--
-- The *.def data files, the key tables and the fonts are generated by the
-- Python pipeline in the parent directory (`make latex` there) before
-- l3build runs.

module = "nycbullets"

sourcefiles     = {"*.dtx", "*.ins", "*.def", "*.ttf"}
installfiles    = {"*.sty", "*.def", "*.ttf"}
-- The key tables are \input by the documentation.
docfiles        = {"nycbullets-keytable-*.tex", "nycbullets-credits.tex"}
textfiles       = {"README.md"}

typesetexe   = "lualatex"
typesetfiles = {"nycbullets.dtx"}
typesetruns  = 3

checkengines = {"luatex"}
checkruns    = 1

tdslocations = {
  "fonts/truetype/public/nycbullets/*.ttf",
}

-- Metadata for `l3build upload` (CTAN).  The fonts are CC0, except for
-- the bullets credited in the documentation, which are CC BY 4.0.
uploadconfig = {
  pkg         = "nycbullets",
  author      = "Matthew Leingang",
  license     = {"lppl1.3c", "cc0", "cc-by-4"},
  summary     = "New York City Subway route bullets for LuaLaTeX",
  repository  = "https://github.com/nyumathclinic/nyc-subway-bullets-font",
  bugtracker  = "https://github.com/nyumathclinic/nyc-subway-bullets-font/issues",
  home        = "https://nyumathclinic.github.io/nyc-subway-bullets-font/",
}
