"""
Generate the data files for the nycbullets LaTeX package.

Written into latex/:

  nycbullets-sets.def          the list of sets and their font files
  nycbullets-<set>.def         key -> code point table for one set
  nycbullets-keytable-<set>.tex  documentation table of every bullet in a set
  nycbullets-credits.tex       attribution for bullets that require it
  NYCSubwayBullets-*.ttf       copies of the fonts (for l3build to package)
"""

from __future__ import annotations

import shutil

from . import mapping
from .config import LATEX_DIR, BulletSet, load_config
from .credits import credits_for
from .fontbuild import VERSION

# Fixed, so that regenerating the files from unchanged data changes nothing.
DATE = "2026-10-03"

# No blank lines in these files: one would be a \par where the file is
# first read, which may be in the middle of a paragraph.
HEADER = (
    "% Generated by `nycbullets tex` from data/mappings/{src}.\n"
    "% Do not edit: edit the mapping table and rerun `make latex`."
)


def provides(name: str, what: str) -> str:
    """Expl3 syntax is on until the end of the file."""

    return f"\\ProvidesExplFile{{{name}}}{{{DATE}}}{{{VERSION}}}{{{what}}}"


TEX_SPECIALS = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "$": r"\$",
    "&": r"\&",
    "#": r"\#",
    "^": r"\textasciicircum{}",
    "_": r"\_",
    "%": r"\%",
    "~": r"\textasciitilde{}",
}


def escape(text: str) -> str:
    return "".join(TEX_SPECIALS.get(c, c) for c in text)


def sets_def(sets: list[BulletSet]) -> str:
    lines = [HEADER.format(src="*.tsv"),
             provides("nycbullets-sets.def", "nycbullets sets")]
    for bset in sets:
        lines.append(
            f"\\nycbullets_declare_set:nnn {{{bset.id}}} {{{bset.name}}} "
            f"{{{bset.font_file.name}}}"
        )
    return "\n".join(lines) + "\n"


def set_def(bset: BulletSet, rows: list[mapping.Row]) -> str:
    lines = [HEADER.format(src=bset.mapping_file.name),
             provides(f"nycbullets-{bset.id}.def", f"nycbullets {bset.name} keys")]
    lines.append(f"\\nycbullets_declare_keys:nn {{{bset.id}}}")
    lines.append("  {")
    for r in sorted(rows, key=lambda r: r.codepoint):
        lines.append(f"    {{{r.key}}} {{{r.codepoint:04X}}}")
    lines.append("  }")
    return "\n".join(lines) + "\n"


def keytable(bset: BulletSet, rows: list[mapping.Row]) -> str:
    lines = [HEADER.format(src=bset.mapping_file.name)]
    lines.append(f"\\begin{{nycbulletstable}}{{{bset.id}}}{{{escape(bset.family)}}}")
    for r in sorted(rows, key=lambda r: r.codepoint):
        lines.append(
            f"\\nycbulletsrow{{{r.key}}}{{{r.codepoint:04X}}}"
            f"{{{escape(r.description)}}}"
        )
    lines.append("\\end{nycbulletstable}")
    return "\n".join(lines) + "\n"


def credits_tex(files: set[str]) -> str:
    lines = [HEADER.format(src="*.tsv and sources/manifest.json")]
    credits = credits_for(files)
    if not credits:
        lines.append("All of the bullet artwork is in the public domain.")
        return "\n".join(lines) + "\n"
    lines.append("\\begin{itemize}")
    for c in credits:
        lines.append(
            f"\\item \\href{{{c.page}}}{{{escape(c.title)}}} "
            f"by {escape(c.artist)}, {escape(c.license)}."
        )
    lines.append("\\end{itemize}")
    return "\n".join(lines) + "\n"


def run() -> None:
    sets, all_set = load_config()
    every = [*sets, all_set]

    LATEX_DIR.mkdir(parents=True, exist_ok=True)
    (LATEX_DIR / "nycbullets-sets.def").write_text(sets_def(every))

    files: set[str] = set()
    for bset in every:
        rows = mapping.read_table(bset.mapping_file)
        files |= {r.file for r in rows}
        if msgs := mapping.problems(rows):
            raise SystemExit(f"{bset.mapping_file.name}: {msgs[0]}")
        (LATEX_DIR / f"nycbullets-{bset.id}.def").write_text(set_def(bset, rows))
        (LATEX_DIR / f"nycbullets-keytable-{bset.id}.tex").write_text(
            keytable(bset, rows))
        if not bset.font_file.exists():
            raise SystemExit(f"{bset.font_file} missing; run `nycbullets build`")
        shutil.copy2(bset.font_file, LATEX_DIR / bset.font_file.name)
        print(f"latex/nycbullets-{bset.id}.def: {len(rows)} keys")

    (LATEX_DIR / "nycbullets-credits.tex").write_text(credits_tex(files))
    print("latex/nycbullets-credits.tex")
